### ISSUE TITLE
install error with pip

### ISSUE THREAD

**Issue by carlosmatthews** [0ssamaak0/DLTA-AI#55]
version = pip 23.2  (python 3.8)
```
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      <string>:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "<string>", line 127, in get_numpy_status
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "c:\users\carlos\workspace\trackia-env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\carlos\workspace\trackia-env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\carlos\workspace\trackia-env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\carlos\AppData\Local\Temp\pip-build-env-zmrkanjx\overlay\Lib\site-packages\setuptools\build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\carlos\AppData\Local\Temp\pip-build-env-zmrkanjx\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\carlos\AppData\Local\Temp\pip-build-env-zmrkanjx\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 236, in <module>
        File "<string>", line 220, in setup_package
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by 0ssamaak0** [comment]
try
```
pip install numpy==1.24.3
```
Then try to install again

**Comment by zhuqiming678** [comment]
python version upper 3.9 cannot support lap, we need install lapx:
pip install lapx

**Comment by 0ssamaak0** [comment]
It's recommended to use `python 3.8` to avoid sth like this. Please check the [installation guide in the docs](https://0ssamaak0.github.io/DLTA-AI/installation/full-installation/#create-a-virtual-environment)
